import type { ReviewContext } from '../model/context.ts';
import type { Explanation } from '../model/explanation.ts';
import { CERTAINTY_LABEL, type Finding, type Review, VERDICT_LABEL } from '../model/finding.ts';
import { escapeMarkdownKeepCode, fence, plural } from '../util/text.ts';

/**
 * Text in these reports comes from the change (titles, paths, branch names, code) or from a model
 * that read it, and review.md also becomes the CI job summary. Escape it so it renders as text:
 * no links, images, HTML, or headings it did not ask for. Inline `code` stays code.
 */
const md = (text: string) => escapeMarkdownKeepCode(text);

/** A code span for a path or command that cannot be closed or broken by its content. */
const code = (text: string) => `\`${text.replace(/`/g, "'").replace(/\r?\n/g, ' ')}\``;

function footer(context: ReviewContext | undefined, provider: string): string {
  if (!context) return `<sub>Generated by Covi (${md(provider)}).</sub>`;
  const { base, head } = context.change;
  return `<sub>Generated by Covi (${md(provider)}) · ${md(base.ref)} ${code(base.sha.slice(0, 7))} → ${md(head.ref)} ${code(head.sha.slice(0, 7))}</sub>`;
}

export function renderExplanation(e: Explanation, context?: ReviewContext): string {
  const out: string[] = [`# ${md(e.headline)}`, '', md(e.summary), ''];
  const evidence = e.intent.evidence.length
    ? ` Evidence: ${e.intent.evidence.map(md).join('; ')}.`
    : '';
  out.push(
    `**Why:** ${md(e.intent.statement)} _(confidence: ${e.intent.confidence}.${evidence})_`,
    '',
  );
  if (e.behavior && (e.behavior.before || e.behavior.after || e.behavior.notes)) {
    out.push('## Behavior', '');
    out.push(`- User-visible: ${e.behavior.userVisible ? 'yes' : 'no'}`);
    if (e.behavior.before) out.push(`- **Before:** ${md(e.behavior.before)}`);
    if (e.behavior.after) out.push(`- **After:** ${md(e.behavior.after)}`);
    if (e.behavior.notes) out.push(`- ${md(e.behavior.notes)}`);
    out.push('');
  }
  if (e.changes.length) {
    out.push('## What changed', '');
    for (const c of e.changes) out.push(`- **${md(c.area)}**: ${md(c.description)}`);
    out.push('');
  }
  if (e.architecture.length) {
    out.push('## Architecture', '');
    for (const a of e.architecture) out.push(`- ${md(a)}`);
    out.push('');
  }
  if (e.details.length) {
    out.push('## Implementation details', '');
    for (const d of e.details) out.push(`- ${md(d)}`);
    out.push('');
  }
  if (e.reviewerNotes.length) {
    out.push('## Before you read the diff', '');
    for (const n of e.reviewerNotes) out.push(`- ${md(n)}`);
    out.push('');
  }
  if (e.readingOrder.length) {
    out.push('## Suggested reading order', '');
    for (const [i, step] of e.readingOrder.entries())
      out.push(`${i + 1}. ${code(step.path)}: ${md(step.reason)}`);
    out.push('');
  }
  if (e.ambiguities.length) {
    out.push('## Open questions', '');
    for (const a of e.ambiguities) out.push(`- ${md(a)}`);
    out.push('');
  }
  out.push('---', footer(context, e.generatedBy?.provider ?? 'agent'), '');
  return out.join('\n');
}

export function locationText(f: Pick<Finding, 'location'>): string {
  if (!f.location) return '';
  return f.location.line ? `${f.location.path}:${f.location.line}` : f.location.path;
}

export function renderReview(
  review: Review,
  explanation?: Explanation,
  context?: ReviewContext,
): string {
  const title = explanation?.headline ?? (context ? context.intent.summary : 'Code change');
  const out: string[] = [
    `# Review: ${md(title)}`,
    '',
    `**${VERDICT_LABEL[review.verdict]}**: ${md(review.summary)}`,
    '',
  ];
  if (review.findings.length) {
    out.push('## Findings', '');
    review.findings.forEach((f, i) => {
      out.push(`### ${i + 1}. ${md(f.title)}`, '');
      const where = locationText(f);
      out.push(
        `**${CERTAINTY_LABEL[f.certainty]}** · ${f.severity} · ${f.category}${where ? ` · ${code(where)}` : ''}`,
        '',
      );
      out.push(md(f.explanation), '');
      out.push('Evidence:', '', fence(f.evidence), '');
      if (f.suggestion) out.push(`**Suggestion:** ${md(f.suggestion)}`, '');
    });
  }
  if (review.tests) {
    const t = review.tests;
    out.push('## Tests', '');
    out.push(
      `${code(t.command)}: ${t.passed ? 'passed' : t.timedOut ? 'timed out' : `failed (exit ${t.exitCode})`} in ${(t.durationMs / 1000).toFixed(1)}s`,
      '',
    );
    if (!t.passed && t.outputTail)
      out.push(fence(t.outputTail.split('\n').slice(-30).join('\n')), '');
  }
  if (review.checked.length) {
    out.push(
      '## What Covi checked',
      '',
      `<details><summary>${review.checked.length} checks</summary>`,
      '',
    );
    for (const c of review.checked) out.push(`- ${md(c)}`);
    out.push('', '</details>', '');
  }
  if (review.notVerified.length) {
    out.push('## Not verified', '');
    for (const n of review.notVerified) out.push(`- ${md(n)}`);
    out.push('');
  }
  if (review.dismissed.length) {
    out.push('## Dismissed', '');
    for (const d of review.dismissed) out.push(`- ${code(d.id)}: ${md(d.reason)}`);
    out.push('');
  }
  out.push('---', footer(context, review.generatedBy.provider), '');
  return out.join('\n');
}

export type SummaryFormat = 'markdown' | 'text';

/** A compact summary for pull/merge request descriptions, changelogs, or chat. */
export function renderSummary(
  e: Explanation,
  review: Review | undefined,
  context: ReviewContext,
  format: SummaryFormat = 'markdown',
): string {
  if (format === 'text') {
    const verdict = review
      ? ` Review: ${VERDICT_LABEL[review.verdict].toLowerCase()}${review.findings.length ? ` (${plural(review.findings.length, 'finding')})` : ''}.`
      : '';
    return `${e.headline}. ${e.summary}${verdict}\n`;
  }
  const out = [`## ${md(e.headline)}`, '', md(e.summary), ''];
  if (e.changes.length) {
    out.push('**Changes**', '');
    for (const c of e.changes.slice(0, 6)) out.push(`- **${md(c.area)}**: ${md(c.description)}`);
    out.push('');
  }
  const focus: string[] = [];
  if (review)
    for (const f of review.findings.slice(0, 3))
      focus.push(`${md(f.title)} (${CERTAINTY_LABEL[f.certainty].toLowerCase()})`);
  if (focus.length === 0)
    for (const step of e.readingOrder.slice(0, 2))
      focus.push(`${code(step.path)}: ${md(step.reason)}`);
  if (focus.length) {
    out.push('**Review focus**', '');
    for (const f of focus) out.push(`- ${f}`);
    out.push('');
  }
  const t = context.tests;
  out.push('**Testing**', '');
  if (review?.tests)
    out.push(`- ${code(review.tests.command)} ${review.tests.passed ? 'passes' : 'fails'}`);
  if (t.addedTestCases || t.changedTestFiles.length)
    out.push(
      `- ${plural(t.addedTestCases, 'test case')} added across ${plural(t.changedTestFiles.length, 'test file')}`,
    );
  else out.push('- No test changes');
  out.push('');
  return out.join('\n');
}
